on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R petstore tests

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        working-directory: samples/client/petstore/R
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        working-directory: samples/client/petstore/R
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        working-directory: samples/client/petstore/R

      - name: Build and test R package
        working-directory: samples/client/petstore/R
        run: build_and_test.bash
